#%RAML 1.0 NamedExample
phoneNumber: !include contact-example.raml
faxNumber: !include contact-fax-example.raml
email: !include contact-email-example.raml
website: !include contact-website-example.raml
