#%RAML 1.0 NamedExample
companyIdentification: !include example-1.raml
companyName: 'GRAYDON BELGIË NV'
alternateCompanyName: 'GRAYDON BELGIQUE NV'
tradeNames:
  - 'GRAYDON'
  - 'MARKTSELECT'
  - 'CREDITEL'
  - 'ACM'
  - 'IT FACILITY MANAGEMENT'
companyAddress: !include example-2.raml
contactInformation: !include example-3.raml
legalForm: !include example-4.raml
size: !include example-5.raml
industry:
  - !include example-6.raml
activities: !include example-7.raml
isActive: "true"
foundationDate: 1940-07-11
dissolutionDate: 2007-01-01
nonEmailIndicator: true
#numberOfBranchOffices: 0
