#%RAML 1.0 DataType
type: object
displayName: User
properties:
  id:
    displayName: Id
  username:
    displayName: Username
  firstName:
    displayName: First Name
  lastName:
    displayName: Last Name
  profilePhoto:
    displayName: Profile photo
  email:
    displayName: Email
  age: integer
  newsletter: boolean
