#%RAML 1.0
title: API body demo
version: v1
baseUri: http://.domain.com/

mediaType: [application/json, application/xml]
protocols: [HTTP, HTTPS]

uses:
  ExampleType: resourceTypes/example-types.raml
types:
  AppPerson: !include resourceTypes/app-person.raml
  Product: !include resourceTypes/product.raml
  NewDataType:
    description: This is a new DataType
    type: object
    properties:
      newProperty:
        required: true
        minLength: 1
        maxLength: 40
        example: This is a new DataType
        description: Property description
        default: This is a new DataType
        type: string
      otherScalar: number
      complex:
        type: object
        properties:
          propA:
            type: string
            example: prop A example
          propB:
            type: string
            example: prop B example
            default: Prop B default value
          propC:
            type: number
traits:
  Paginated: !include traits/pagination.raml
  Adminable: !include traits/adminable.raml

/people:
  displayName: People
  post:
    body:
      application/json:
        type: AppPerson
      application/xml:
        type: !include schemas/person.xsd
        example: !include examples/person.xml
  put:
    body:
      application/json:
        schema: !include schemas/person.json
        example: !include examples/person.json
      application/xml:
        type: !include schemas/person.xsd
        example: !include examples/person.xml
  /{personId}:
    put:
      body:
        application/json:
          type: AppPerson
        application/xml:
          type: !include schemas/person.xsd
          example: !include examples/person.xml
/products:
  post:
    body:
      application/json:
        type: Product
      application/xml:
        type: !include schemas/product.xsd
        example: !include examples/product.xml
/orgs:
  /{orgId}:
    put:
      body:
        application/json:
          type: ExampleType.Org
          properties:
            id:
              type: string
              description: UUID generated ID
/messages:
  post:
    is: [Adminable]
    body:
      application/json:
        type: object
        properties:
          receiver:
            type: string
            description: receiver of the message
            required: true
          body:
            type: string
            description: A message body
            required: true
          important:
            type: boolean
            description: If true then the message will be marked as important
            default: false
            required: true
  /bulk:
    post:
      is: [Adminable]
      body:
        application/json:
          type: array
          items: !include resourceTypes/message-sent-type.raml
          examples:
            Example1: !include examples/messages-sent-example.json
/arrayBody:
  post:
    body:
      application/json:
        description: |
          This demonstrates a body as an Array
        type: AppPerson[]
/ramlTypeTest:
  post:
    body:
      application/json:
        type: NewDataType
/urlencoded:
  post:
    body:
      application/x-www-form-urlencoded:
        type: Product
/union:
  post:
    body:
      application/x-www-form-urlencoded:
        type: ExampleType.Alertable
/files:
  /multipart:
    post:
      body:
        multipart/form-data:
          description: The file to be uploaded.
          properties:
            file1:
              type: file
            file2:
              type: string
  /file:
    post:
      body:
        image/png:
          type: file
