#%RAML 1.0 NamedExample
- #Item 1
  addressType: 'REGISTERED-OFFICE-ADDRESS'
  streetName: 'UITBREIDINGSTRAAT'
  houseNumber: '84'
  houseNumberAddition: '/1'
  postalCode: '2600'
  city: 'BERCHEM (ANTWERPEN)'
  country: 'Belgium'
  countryCode: 'BE'
  fullFormatedAddress: "UITBREIDINGSTRAAT 84 /1, 2600 BERCHEM (ANTWERPEN), BELIUM"
#  addressClassification: !include AddressClassification_BE-Example-1.raml