value:
  "customerId": "US52949186"
  "doctorId": ""
  "customerStatus": "A"
  "customerTypeCode": "OPCR"
  "customerSubTypeCode": "MEDGRP"
  "primarySpecialtyCode": ""
  "primarySpecialtyDescr": ""
  "nameData":
    "name": "JOHN DOE SKIN AND VEIN CENTER"
    "firstName": ""
    "lastName": ""
    "middleName": ""
    "salutation": ""
    "designation": ""

  "affiliations":
    -
      "affiliationId": "72824633"
      "affiliationName": "MULTIPLE DOCTORS"
      "secAffiliationId": ""
      "secAffiliationName": ""
      "addresses":
        -
          "addressIndicator": ""
          "addressId": ""
          "addressType": ""
          "addressLine1": ""
          "addressLine2": ""
          "addressLine3": ""
          "city": ""
          "stateProvinceCode": ""
          "postalCode": ""
          "postalCodeExt": ""
          "country": "US"
    -
      "affiliationId": "15200973"
      "affiliationName": "JANE Doe"
      "secAffiliationId": ""
      "secAffiliationName": ""
      "addresses":
        -
          "addressIndicator": ""
          "addressId": ""
          "addressType": ""
          "addressLine1": ""
          "addressLine2": ""
          "addressLine3": ""
          "city": ""
          "stateProvinceCode": ""
          "postalCode": ""
          "postalCodeExt": ""
          "country": "US"
  "addresses":
    -
      "addressIndicator": ""
      "addressId": "15200973"
      "addressType": "CALL"
      "addressLine1": "7110 JOHN AVE"
      "addressLine2": ""
      "addressLine3": ""
      "city": "WILMINGTON"
      "stateProvinceCode": "NC"
      "postalCode": "28403"
      "postalCodeExt": ""
      "country": "US"
    -
      "addressIndicator": ""
      "addressId": "232323"
      "addressType": "MAIL"
      "addressLine1": "1 JOHN AVE"
      "addressLine2": ""
      "addressLine3": ""
      "city": "WILMINGTON"
      "stateProvinceCode": "NC"
      "postalCode": "28403"
      "postalCodeExt": ""
      "country": "US"
  "contacts":
    -
      "phone": ""
      "phone2": ""
      "email": ""
      "fax": ""
      "webAddress": ""
