#%RAML 1.0
title: My super cool, example API
version: v1
baseUri: http://{environment}.api.domain.com/{version}/
mediaType: [ application/json, application/xml ]

annotationTypes:
  MarkAnnotation: nil
  deprecated: string
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true

/test:
  get:
    headers:
      x-deprecated:
        (deprecated): |
          This property is deprecated.

          Please, do not use it in new projects.
        type: string
        required: false
        displayName: Deprecated
        minLength: 0
        maxLength: 100
        pattern: "[a-zA-Z]*"
        description: |
          This is a description
        examples:
          Googd: ""
          Bad: "something"
      x-enumerable:
        (MarkAnnotation):
        (clearanceLevel):
          level: low
          signature: 230-ghtwvfrs1itr
        type: string
        displayName: Enumerable 1
        description: |
          Example enumerable type to test the documentation
          element.

          It renders `Markdown` model.
        enum: [v1, v2, v3, v4]
        required: false
        examples:
          Version1: v1
          Version2: v2
        pattern: "v[1-4]"
        default: v1
      x-repeat:
        type: array
        items: string
        description: |
          Hello world
      x-unionable:
        type: string | number
      Accept:
        type: string
        default: application/json
        description: |
          Supported mime tyes in this API are:

          - `application/json`
          - `application/xml`
          - `application/x-vnd.unknown`
