#%RAML 1.0
title: Oauth 2.0 example
version: v1
baseUri: http://domain.api.domain.com/{version}/

annotationTypes:
  oauth-2-custom-settings: !include oauth-2-custom-settings.raml

securitySchemes:
  oauth2Normal:
    type: OAuth 2.0
    displayName: Normal OAuth 2.0 definition
    settings:
      accessTokenUri: https://token.com
      authorizationUri: https://auth.com
      authorizationGrants: implicit
      scopes: [profile, email]
    describedBy:
      queryParameters:
        access_token:
          type: string
          description: Apply access token here.
      headers:
        Authorization:
          type: string
  oauth2:
    type: OAuth 2.0
    displayName: OAuth 2.0 with annotation
    settings:
      (oauth-2-custom-settings):
        # ignoreDefaultGrants:
        authorizationGrants: [annotated_custom_grant, annotated_custom_grant2]
        authorizationSettings:
          queryParameters:
            resource:
              type: string
              required: true
              description: |
                A resource ID that defines a domain of authorization.
              displayName: Hello query parameeter
              default: default
              examples:
                named: named example value
                otherExample: test example value
              pattern: "[a-zA-Z]+"
              maxLength: 12
              minLength: 3
              required: true
            numericParam:
              type: number
              minimum: 10
              maximum: 20
              multipleOf: 2
              format: float
              required: false
              example: 22
            dateParam:
              type: date-only
              required: false
            repetableParam1:
              type: string[]
              required: false
            repetableParam2:
              type: array
              items: integer
              required: false
        accessTokenSettings:
          queryParameters:
            queryTokenResource: string
            detailedTokenResource:
              type: number
              description: some description
              required: false
          headers:
            x-token-resource:
              type: number
              default: 123
          body:
            bodyTokenResource: string
            bodyDetailed:
              type: boolean
              required: true
              displayName: Body detailed property
              default: true
      accessTokenUri: https://token.com
      authorizationUri: https://auth.com
      authorizationGrants: [implicit, authorization_code]
      scopes: [profile, email]
    describedBy:
      queryParameters:
        access_token:
          type: string
          description: Apply access token here.
  basic:
    type: Basic Authentication
  digest:
    type: Digest Authentication
  pass:
    type: Pass Through
  oauth1: !include oauth_1_0.raml
  custom1: !include x-custom.raml
  custom2: !include x-other.raml
/oauth2:
  get:
    securedBy: [oauth2]
  post:
    securedBy: [oauth2Normal, oauth2]
  put:
    securedBy: [null, oauth2]
/basic:
  get:
    securedBy: [basic]
/digest:
  get:
    securedBy: [digest]
/pass:
  get:
    securedBy: [pass]
    queryParameters:
      exampleTest:
        examples:
          example1: hello example
          example2: Other example
/oauth1:
  get:
    securedBy: [oauth1]
/custom1:
  get:
    securedBy: [custom1]
/custom2:
  get:
    securedBy: [custom2]
/combo:
  get:
    securedBy: [null, basic, digest, pass, oauth1, oauth2Normal, custom1, custom2]
