#%RAML 1.0
title: Annotation API
version: v1
baseUri: http://api.domain.com/

annotationTypes:
  annotationTest: nil
  deprecated: string
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true
types:
  ErrorResource:
    (deprecated): This resource type is deprecated and will be removed in the next version.
    description: A response that is errored
    type: object
    properties:
      error:
        type: boolean
        required: true
        example: true
        default: true
        description: Indicate that the response is errored.
      message:
        type: string
        description: The error message associated with the error.
        example: <<example>>
        required: true
  notRequiredRepeatable:
    (annotationTest):
    type: object
    required: false
    properties:
      test: boolean
  ComplexAnnotations:
    (clearanceLevel):
      level: high
      signature: 230-ghtwvfrs1itr
    type: object
    properties:
      test: string
  ComboType:
    (annotationTest):
    (deprecated): This is deprecated annotation
    (clearanceLevel):
      level: low
      signature: OtherSignature
    type: object
    properties:
      test: string
  NoAnnotations:
    type: object
    properties:
      test: string
