#%RAML 1.0 NamedExample
restore-user-202-response-example:
  - context: response
    code: HTTP 202
    short-description: 1 user record have been accepted to be restored later
  - context: confirmation
    code: "123456789"