#%RAML 1.0 NamedExample
user-patch-202-cds-response-example:
  - context: response
    code: HTTP 202
    short-description: 1 user record have been accepted to be updated later
  - context: confirmation
    code: "123456789"