#%RAML 1.0 NamedExample
users-patch-request-example::
  user-address:
    context: home
    line1: 3388 Hamilton St
    line2: Apt 1
    city: Philadelphia
    state-region-code: PA
    state-region-name: Pennsylvania
    country: USA
    postal-code: "19104"
    additional-postal-code: "0388"
    validity: Valid
    preference-index: 3
