#%RAML 1.0 NamedExample
users-post-single-input-200-response-example:
  - user-id: ABCD1234
    user-name: George Castanza
    user-date-of-birth: 2000-01-01
    user-address:
      context: home
      line1: 3388 Hamilton St
      line2: Apt 1
      city: Philadelphia
      state-region-code: PA
      state-region-name: Pennsylvania
      country: USA
      postal-code: "19104"
      additional-postal-code: "0388"
      validity: Valid
      preference-index: 3