#%RAML 1.0 NamedExample
users-archive-action-200-response-example:
  archived-location: \\DCS001AB\user-archive-folder
  archive-completed-time: 2018-08-10T13:11:46.449Z
  number-of-records-archived: 17225