#%RAML 1.0 NamedExample
users-delete-202-cds-response-example:
  - context: response
    code: HTTP 202
    short-description: 2 user records have been accepted to be deleted later
  - context: confirmation
    code: "123456789"
    short-description: confirmation of record 1
  - context: confirmation
    code: 1234aaaa
    short-description: confirmation of record 2