#%RAML 1.0 NamedExample

createQuotePostRequestExample:
  displayName: An example of the POST Request for createquote
  value:
    titleCode: "MR"
    firstName: "John"
    lastName: "Doe"
    dateOfBirth: "2001-01-01"
    maritalStatusCode: "M"
    addressLine1: "Dun-roamin"
    addressLine2: "1 Back Gate"
    addressLine3: "Victoria St"
    addressLine4: "Spalding"
    addressLine5: "Lincolnshire"
    postCode: "PE11 1EA"
    maskCode: "ABC"
    product: "Car"
    clientId: "5656565656565"