#%RAML 1.0 NamedExample

createQuotePostMatchedExample:
  displayName: An example of the POST Response for createquote, when the account matches the one in the request
  value:
    customerAccountId: "WES456789"
    quoteId: "WES456789-01"
    titleCode: "MR"
    title: "Mr"
    firstName: "John"
    lastName: "Doe"
    existingCustomer: true