#%RAML 1.0 NamedExample

createQuotePostCreatedExample:
  displayName: An example of the POST Response for createquote, when the account has been created
  value:
    customerAccountId: "WES456789"
    quoteId: "WES456789-01"
    existingCustomer: false