#%RAML 1.0 NamedExample

validCredentials:
  displayName: Valid Credentials Api Customer
  value:
    customerAccountId : "123456789"
    quoteId : "TED456789-01"
    isTE : true
    affinityCode : "BIS1"

validCredentialsOLSS:
  displayName: Valid Credentials OLSS
  value:
    customerAccountId : "123456789"
    quoteId : "123456789-01"
    isTE : false
    affinityCode : "BIS1"