#%RAML 1.0 NamedExample

validate_customer_account_hash_request:
  displayName: A POST Validate Customer Account Hash Request Example
  description: A POST Validate Customer Account Hash Request Example
  value:
     encryptedHash: "XXXXXXXXX"