#%RAML 1.0 NamedExample

ValidatePingCustomerAccountsPostExample:
  displayName: An example of the POST Request for validating PING customer
  value:
    firstName : "John"
    lastName : "Smith"
    dateOfBirth : "2019-03-03"