#%RAML 1.0 NamedExample

no_ping_userId_and_multiple_customer_returned_example:
  displayName: Validate Credentials successful response with no userId
  value:
    - #1st entry
      customerAccountId: "123456789"
      passwordMatched: true
    - #2nd entry
      customerAccountId: "123456799"
      passwordMatched: true   

ping_userId_and_one_customer_returned_example:
  displayName: Validate Credentials successful single response with userId
  value:
    - #1st entry
      customerAccountId: "123456789"
      userId: "3141933d-1ed3-40e6-bff8-5c9a4ad10ac4"
      passwordMatched: false

ping_userId_and_multiple_customer_returned_example:
  displayName: Validate Credentials successful multiple response with one userId
  value:
    - #1st entry
      customerAccountId: "123456789"
      userId: "3141933d-1ed3-40e6-bff8-5c9a4ad10ac4"
      passwordMatched: true
    - #2nd entry
      customerAccountId: "123456799"
      passwordMatched: false