#%RAML 1.0 NamedExample
addressType: 'REGISTERED-OFFICE-ADDRESS'
streetName: 'HULLENBERGWEG'
houseNumber: '250'
city: 'AMSTERDAM ZUIDOOST'
country: 'Netherlands'
countryCode: 'NL'
fullFormatedAddress: 'HULLENBERGWEG 250, 1101BV AMSTERDAM ZUIDOOST'