#%RAML 1.0 NamedExample
- #Item 1
  addressType: 'REGISTERED-OFFICE-ADDRESS'
  streetName: 'HULLENBERGWEG'
  houseNumber: '250'
  city: 'AMSTERDAM ZUIDOOST'
  country: 'Netherlands'
  countryCode: 'NL'
  fullFormatedAddress: 'HULLENBERGWEG 250, 1101BV AMSTERDAM ZUIDOOST'
- #Item 2
  addressType: 'REGISTERED-OFFICE-ADDRESS'
  streetName: 'MYSTREET'
  houseNumber: '000'
  city: 'AMSTERDAM ZUIDOOST'
  country: 'Netherlands'
  countryCode: 'NL'
  fullFormatedAddress: 'MYSTREET 000, 1101BV AMSTERDAM ZUIDOOST'
