#%RAML 1.0 NamedExample
addressType: 'REGISTERED-OFFICE-ADDRESS'
streetName: 'UITBREIDINGSTRAAT'
houseNumber: '1'
houseNumberAddition: '/1'
postalCode: '1234'
city: 'BERCHEM (ANTWERPEN)'
country: 'Belgium'
countryCode: 'BE'
fullFormatedAddress: "UITBREIDINGSTRAAT 1 /1, 1234 BERCHEM (ANTWERPEN), BELGIUM"
