#%RAML 1.0 NamedExample
- #Item 1
  addressType: 'REGISTERED-OFFICE-ADDRESS'
  building: 'FITZWILLIAMHOUSE BUILDING'
  streetName: '128 St Marry Axe'
  streetNameAdd1: '128 St Marry Axe, EP1 1BE'
  country: 'United Kingdom'
  countryCode: 'GB'
  fullFormatedAddress: 'FITZWILLIAMHOUSE BUILDING, 128 St Marry Axe, London, EP1 1BE'
