#%RAML 1.0 NamedExample
companyIdentification: !include CompanyIdentification_BE_Example-1.0.raml
companyName: 'ACME BE'
alternateCompanyName: 'ACME ALT NV'
tradeNames:
  - 'ACME'
  - 'ACM'
  - 'IT FACILITY MANAGEMENT'
companyAddress: !include Addresses_BE_Example-1.0.raml
legalForm: !include CompanyLegalForm_BE_Example-1.0.raml
isActive: "true"
foundationDate: 1940-07-11
dissolutionDate: 2007-01-01
nonEmailIndicator: true
