#%RAML 1.0 NamedExample
error-example:
  value:
    transaction-id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
    type: Data error 
    message: String value was expected but number value received
    time: 2018-05-31T15:00:06,325Z