#%RAML 1.0 Library

types:
 UpdateCredentials:
    properties:
      encryptedPassword:
        description: Existing password on account in encrypted format.
      newEncryptedPassword?:
        description: New password to be set on account in encrypted format.
      newUserName?:
        description: Email Address as username to be updated on account.