#%RAML 1.0 Library

types:
  
  PingValidateCredentialsResponse:
    properties:
      customerAccountId:
        type: string
        required: true
      userId:
        type: string
        required: false
      passwordMatched:
        type: boolean
        required: true
         