#%RAML 1.0 Library
usage: This library offers shared error responses for System Traits.

types: 
  Error:
    properties:
      messages : Messages[]
      
  Messages:
    properties:
        code: 
        description:
