#%RAML 1.0 NamedExample
cordCreateRequestExample:
  allOrNone: false
  records:
    -
      attributes:
        type: "Inventory__c"
      Name: "70226"
      AS400Location: "OMANE"
      AS400CityName: "Omaha, DG"
      Year: "2016"
      Make: "FRT"
      Model: "CASCADIA"
      ModelType: "CAS"
      Type: "OOP"
      Weight: 9300
      Serial: "ABCDEF123"
      AcquiredDate: "2019-01-16"
      InService: "2019-01-16"
      MaintenanceCode: "V9"
      MaintenanceCodeDescription: "V9"
      AS400ECM: 401571.60
      AS400Status: "INVTM"
      IQDate: "2019-01-16"
      Engine: "D13"
      EngineSerial: "ABC123"
      EngineWarranty: "2019-01-16"
      EngineArrangement: "ABC123"
      TransmissionSerial: "ABC123"
      TransmissionRearRatio: 1
      TransmissionRearRearSN: "1"
      TransmissionFrontRearSN: "1"
      BookValue: 10000
      BookValueAsOf: "2019-01-16"
      Depreciation: 10
      Age: 1
      AssetDescription: "Asset"
      CabType: "A"
      Color: "BLUE"
      TCUType: "THERMOKING"
      TCUHours: 12
      Length: 12
      Axles: 14
      InventoryType: Tractor
    -
      attributes:
        type: "Inventory__c"
      Name: "70227"
      AS400Location: "OMANE"
      AS400CityName: "Omaha, DG"
      Year: "2016"
      Make: "FRT"
      Model: "CASCADIA"
      ModelType: "CAS"
      Type: "OOP"
      Weight: 9300
      Serial: "ABCDEF123"
      AcquiredDate: "2019-01-16"
      InService: "2019-01-16"
      MaintenanceCode: "V9"
      MaintenanceCodeDescription: "V9"
      AS400ECM: 401571.60
      AS400Status: "INVTM"
      IQDate: "2019-01-16"
      Engine: "D13"
      EngineSerial: "ABC123"
      EngineWarranty: "2019-01-16"
      EngineArrangement: "ABC123"
      TransmissionSerial: "ABC123"
      TransmissionRearRatio: 1
      TransmissionRearRearSN: "1"
      TransmissionFrontRearSN: "1"
      BookValue: 10000
      BookValueAsOf: "2019-01-16"
      Depreciation: 10
      Age: 1
      AssetDescription: "Asset"
      CabType: "A"
      Color: "BLUE"
      TCUType: "THERMOKING"
      TCUHours: 12
      Length: 12
      Axles: 14
      InventoryType: Tractor
