#%RAML 1.0 Library
types:
  property: !include ../data-types/dataType-property.raml
  properties:
    displayName: Entity Properties
    description: A collection of entity properties
    type: property[]