#%RAML 1.0 Library
types:
  performance-node: !include ../data-types/dataType-performance-node.raml
  performance-nodes:
    displayName: Performance Nodes
    description: A collection of performance nodes
    type: performance-node[]
    