#%RAML 1.0 Library
types:
  basic-questions-set: !include ../data-types/dataType-basic-questions-set.raml
  basic-questions-sets:
    displayName: Basic Questions Array
    description: Basic Questions Array
    type: basic-questions-set[]
