#%RAML 1.0 Library
traits:
  selectable: !include ../traits/trait-selectable.raml
  traceable: !include ../traits/trait-traceable.raml
  routable: !include ../traits/trait-routable.raml
  pageable: !include ../traits/trait-pageable.raml
  filterable: !include ../traits/trait-filterable.raml
  performance-monitorable: !include ../traits/trait-performance-monitorable.raml
  sortable: !include ../traits/trait-sortable.raml
  asynchronously-callable: !include ../traits/trait-asynchronously-callable.raml
  identifyable: !include ../traits/trait-identifyable.raml