#%RAML 1.0 Library
types:
  social-media-account: !include ../data-types/dataType-social-media-account.raml
  social-media-accounts:
    displayName: Social Media Accounts
    description: A collection of social media accounts
    type: social-media-account[]