#%RAML 1.0 Library
types:
  email-address: !include ../data-types/dataType-email-address.raml
  email-addresses:
    displayName: Email Addresses
    description: A collection of email addresses
    type: email-address[]
