#%RAML 1.0 Library
types:
  document-statistic: !include ../data-types/dataType-document-statistic.raml
  content-data: !include ../data-types/dataType-content-data.raml
  content-metadata: !include ../data-types/dataType-content-metadata.raml