#%RAML 1.0 Library
types:
  code-description: !include ../data-types/dataType-code-description.raml
  code-descriptions:
    displayName: Code Descriptions123
    description: a collection of code descriptionsabc
    type: code-description[]