#%RAML 1.0
title: My super cool, example API
version: v1
baseUri: http://api.domain.com/

mediaType: [application/json, application/xml]

annotationTypes:
  MarkAnnotation: nil
  deprecated: string
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true

types:
  Image: !include resourceTypes/image.raml
  Resource: !include resourceTypes/resource.raml
  AppPerson: !include resourceTypes/app-person.raml
  Product: !include resourceTypes/product.raml
  EnurableType:
    (MarkAnnotation):
    description: |
      Test description for a type.
    type: object
    minProperties: 2
    maxProperties: 12
    examples:
      NormalExample:
        e1: v1
        e2: e2
      OtherExample:
        e1: v4
        e2: e4
    properties:
      e1:
        (MarkAnnotation):
        (deprecated): |
          This property is deprecated.

          Please, do not use it in new projects.
        (clearanceLevel):
          level: low
          signature: 230-ghtwvfrs1itr
        type: string
        displayName: Enumerable 1
        description: |
          Example enumerable type to test the documentation
          element.

          It renders `Markdown` model.
        enum: [v1, v2, v3, v4]
        required: false
        examples:
          - v1
          - v2
        pattern: "v[1-4]"
        default: v1
      e2:
        type: string
        enum: [e1, e2, e3, e4]
        required: true
        example: e1
  ArrayType:
    (deprecated): Test annotation
    (clearanceLevel):
      level: low
      signature: 012-abcdefghijkl
    type: array
    items: Image
    description: |
      Hello world
  ErrorResource:
    description: A response that is errored
    type: object
    properties:
      error:
        type: boolean
        required: true
        example: true
        default: true
        description: Indicate that the response is errored.
      message:
        type: string
        description: The error message associated with the error.
        example: <<example>>
        required: true
  Feature:
    description: A feature to test enum values in the URI parameters.
    type: number
    enum:
        - 1
        - 2
        - 3
  Unionable:
    type: ErrorResource | Product
  PropertyUnion:
    type: object
    properties:
      etag:
        type: string
      data: Feature | ErrorResource | Product
  PropertyArray:
    type: object
    properties:
      etag:
        type: string
      nextPageToken:
        type: string
      data:
        type: array
        items: Product
      complex:
        type: array
        items: string | number | Product
  ComplexRecursive:
    type: object
    properties:
      iteration1:
        properties:
          images:
            type: array
            items: Image
          userImage:
            type: Image
            properties:
              options:
                type: string | Product
              user:
                type: AppPerson
      ieration2:
        type: Product
        properties:
          images:
            type: Image[]
  ProcessVariableList:
    type: object
    properties:
      //: any
    example: |
      {
        "processVar1": "value1",
        "processVar2": "value2"
      }
  XmlSchema:
    (deprecated): Test annotation
    description: |
      XML type that has only xsd schema and example
    type: !include product.xsd
    example: !include product.xml

/test:
  post:
