#%RAML 1.0
title: Query example
version: v1
baseUri: http://api.domain.com/{version}/

mediaType: application/x-www-form-urlencoded

types:
  FormUrlEncodedType:
    properties:
      grant_type:
        type: string
        description: OAuth2
        enum: [authorization_code, password, client_credentials, refresh_token]
      code:
        type: string
        description: Code property returned by the authorization server.
      redirect_uri:
        type: string
        description: Registered redirect URI
      client_id:
        type: string
        description: Registered client id
  OptionalType:
    type: object
    properties:
      optional1:
        type: string
        required: false
      optional2:
        type: number
        required: false
/endpoint:
  post:
    displayName: Required
    body:
      displayName: Test URL encoded
      type: FormUrlEncodedType
  put:
    displayName: Optional
    body:
      type: OptionalType
  delete:
    displayName: Mixed
    body:
      type: [OptionalType, FormUrlEncodedType]
