#%RAML 1.0
version: v1
title: Schema test
types:
  SchemaType: !include schema.json
/schema-payload:
  get:
    responses:
      200:
        body:
          application/json:
            type: !include schema.json
